AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Parameters:

  TABLENAME:
    Type: String
    Description: The DynamoDB table for storing Todo information.
    Default: 'TodoTable'

  REGIONNAME:
    Type: String
    Description: Default region for deployment.
    Default: 'ap-southeast-1'


Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get




  TodoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todos/
      Handler: app.lambda_handler
      Runtime: python3.7

      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE: !Ref TABLENAME
          REGION: !Ref REGIONNAME

      Events:
        Post:
          Type: Api
          Properties:
            Path: /todos
            Method: post

        Read:
          Type: Api
          Properties:
            Path: /todo-read/{id}
            Method: get

        Get:
          Type: Api
          Properties:
            Path: /todos
            Method: get

        Put:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: put

        Delete:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: delete

  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TABLENAME
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1




Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
